# Service Account for Spark Job
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
---
# Permissions for Spark Job
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "delete", "deletecollection", "patch"]
---
# Role Binding for Spark Job
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
subjects:
- kind: ServiceAccount
  name: spark-sa
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
---
# Spark Job
apiVersion: batch/v1
kind: Job
metadata:
  name: spark-scalability-simulation
spec:
  template:
    spec:
      serviceAccountName: spark-sa
      # driver configurations
      containers:
      - name: spark-driver
        image: spark-demo:v1
        command: ["/opt/spark/bin/spark-submit"]
        args:
          - "--master"
          - "k8s://https://kubernetes.default.svc"
          - "--deploy-mode"
          - "client"
          - "--conf"
          - "spark.executor.instances=2"   # Keep it to 2 for better stability on a laptop
          - "--conf"
          - "spark.kubernetes.container.image=spark-demo:v1"
          - "--conf"
          - "spark.executor.memory=1g"
          - "--conf"
          - "spark.driver.memory=1g"
          - "--conf"
          - "spark.kubernetes.memoryOverheadFactor=0.3" # Increased buffer
          - "/opt/spark/work-dir/spark_script.py"
      restartPolicy: Never
  backoffLimit: 4