FROM apache/spark:3.5.0

WORKDIR /app

USER root
RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install pandas numpy scikit-learn joblib

USER 185
COPY scripts/spark_streaming.py .
COPY ml_model/ /app/ml_model/

# Spark submit path for apache/spark image is /opt/spark/bin/spark-submit
CMD ["/opt/spark/bin/spark-submit", \
    "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.postgresql:postgresql:42.6.0", \
    "spark_streaming.py"]
